### ISSUE TITLE
Reconsider url paths

### ISSUE THREAD

**Issue by BradfordMedeiros** [GoogleCloudPlatform/k8s-cluster-bundle#166]
Consider this:
File urls a specified from an absolute path, for example:
~~~~
rawTextFiles:
- name: data-blob
  files:
  - url: file:///datablob/some-data.txt
~~~~

However, the file root is based upon the working directory of whatever is passed as the input file -f 
~~~~
func realInlinerMaker(rw files.FileReaderWriter, inputFile string) fileInliner {
	return build.NewInlinerWithScheme(
		files.FileScheme,
		&files.LocalFileObjReader{filepath.Dir(inputFile), rw}, // this gets joined in ioutil.Read for the base path
	)
}
~~~~

So if you were to pass the componnt in directly for datablob, that url is specifying relative to the folder it's already in and therefore is looking for datablob/datablob/some-data.txt which won't exist. 

Does that explanation make sense?

**Comment by Kashomon** [comment]
So I guess the question you're asking is: "could we support relative URL paths in addition to absolute URL paths"?

I used to have support for relative URL paths, but I removed support for relative URL paths in https://github.com/GoogleCloudPlatform/k8s-cluster-bundle/commit/162c53be32b88911ebca73c11b9f2c88ca56968b

Relative paths were problematic for two reasons:

* The bundle object/type adds an extra layer.  So if you inline a bundle, you need to either rewrite the component file paths relative to the bundle or you need to CD to the directory of each component. I went with the former and it was kind of a pain. If I did it again, I'd probably do the latter method.
* Relative paths are often a security problem, because it can allow users to reach into other parts of the filesystem. That's not as huge a problem for bundle building, since bundle-building is intended to be done by a trusted part of the system (or by an individual user). But it could be a problem later.

I'm not opposed to adding it back if you think it's a big win for the user experience.

**Comment by Kashomon** [comment]
This should be fixed now -- I added relative paths back.
