### ISSUE TITLE
Add SecretGenerator Object

### ISSUE THREAD

**Issue by Kashomon** [GoogleCloudPlatform/k8s-cluster-bundle#178]
This is a design idea/concern I've been thinking about and talking to others about. How do we represent secrets in a component or in a bundle? I don't think the Cluster Bundle library should try to do much with secrets (maybe nothing), but it probably needs a story for secrets.

* One option is to just not generate them and rely on controllers to generate them
* Another is to generate them with a CLI and put them into the bundle/component at runtime.
* Another option is to have a bundle-extension object like a SecretGenerater object that gives hints about how to generate secrets.

These aren't all disjoint options, of course.

**Comment by justinsb** [comment]
I agree that these are not exclusive options.

But I would lean towards controllers / operators.   Or an initializer container or Job.

Do we have a use-case where we would want to manage these secrets externally?  The primary use case I can think of is where the secret is an external secret e.g. a GCP ServiceAccount Key - we _could_ have a controller that creates others service account keys, but that then increases the security surface area because we have a more-powerful secret in the cluster than we would otherwise want.

**Comment by Kashomon** [comment]
I was thinking about the SecretGenerator more as a hint about what secrets need to be created by the controllers / operators.

**Comment by Kashomon** [comment]
Another approach (kustomize): https://github.com/kubernetes/enhancements/pull/811/files

(not really compatible with cluster bundle, just noting)

**Comment by BradfordMedeiros** [comment]
To me this seems mechanically similar to what the patch mechanism does.
